dojo_dashboard_I/config/routes.rb
Rails.application.routes.draw do
  root 'dojos#index'
  resources :dojos do
    resources :students
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

dojo_dashboard_I/app/models/dojo.rb
class Dojo < ApplicationRecord
  has_many :students, dependent: :destroy
  
  validates :branch, :street, :city, :state, presence: true
  validates :state, length: { is: 2 }

end

dojo_dashboard_I/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :dojo

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

  def self.with_dojo student_id
    self.joins(:dojo).where("students.id = ?", student_id).select(:id, :first_name, :last_name, :email, :branch, :dojo_id, :created_at).first
  end

  def self.cohort student
    self.where("id != ? AND dojo_id = ? AND DATE(created_at) = ?", student.id, student.dojo_id, student.created_at.strftime("%Y-%m-%d"))
  end
end

dojo_dashboard_I/app/controllers/dojos_controller.rb
class DojosController < ApplicationController
  def index
    @dojos = Dojo.all
  end

  def new
    @dojo = Dojo.new
  end

  def create
    @dojo = Dojo.new(dojo_params)

    if @dojo.save
      redirect_to @dojo, notice: "You have successfully created a Dojo!"
    else
      flash[:errors] = @dojo.errors.full_messages
      redirect_to :back
    end
  end

  def show
    @dojo = Dojo.find(params[:id])
    @students = @dojo.students
  end

  def edit
    @dojo = Dojo.find(params[:id])
  end

  def update
    @dojo = Dojo.find(params[:id])

    if @dojo.update(dojo_params)
      redirect_to root_path, notice: "You have successfully updated a Dojo!"
    else
      flash[:errors] = @dojo.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    Dojo.find(params[:id]).destroy
    redirect_to :root
  end

  private
    def dojo_params
      params.require(:dojo).permit(:branch, :street, :city, :state)
    end
end

dojo_dashboard_I/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @dojos = Dojo.all
    @dojo = Dojo.find(params[:dojo_id])
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to "/dojos/#{@student.dojo_id}", notice: 'You have successfully created a Student!'
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to :back
    end
  end

  def show
    # created custome class method to join the student and the dojo. Look at the Student model
    @student = Student.with_dojo(params[:id])
    # created custom class method. Look at the Student model
    @cohort = Student.cohort(@student)
  end

  def edit
    @dojos = Dojo.all
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to dojo_student_path(@student.dojo_id, @student.id), notice: 'You have successfully updated a Student!'
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    Student.find(params[:id])
    redirect_to :root
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
  end
end

dojo_dashboard_I/app/helpers/dojos_helper.rb
module DojosHelper
end

dojo_dashboard_I/app/helpers/students_helper.rb
module StudentsHelper
end

dojo_dashboard_I/app/views/dojos/edit.html.erb
<h1>Edit <%= @dojo.branch %></h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>	

<form action="/dojos/<%= @dojo.id %>" method="post">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label>Branch:</label>
		<input type="text" name=dojo[branch] value="<%= @dojo.branch %>">
	</p>
	<p>
		<label>Street:</label>
		<input type="text" name=dojo[street] value="<%= @dojo.street %>">
	</p>
	<p>
		<label>City:</label>
		<input type="text" name=dojo[city] value="<%= @dojo.city %>">
	</p>
	<p>
		<label>State:</label>
		<input type="text" name=dojo[state] value="<%= @dojo.state %>">
	</p>
	<input type="submit" name="Update Dojo">	
</form>

<%= link_to "Back", root_path %>

dojo_dashboard_I/app/views/dojos/index.html.erb
<h1>Listing <%= pluralize(@dojos.count, "Dojo") %></h1>

<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

<table>
	<thead>
		<th>Coding Dojo Branch</th>
		<th>Street</th>
		<th>City</th>
		<th>State</th>
		<th>Actions</th>
	</thead>
	<tbody>
		<% @dojos.each do |dojo| %>
		<tr>
			<td><%= dojo.branch %></td>
			<td><%= dojo.street %></td>
			<td><%= dojo.city %></td>
			<td><%= dojo.state %></td>
			<td>
				<%= link_to "Show", dojo %> |
				<%= link_to "Edit", edit_dojo_path(dojo) %> | 
				<%= link_to "Delete", dojo, data: { method: :delete, confirm: "Are you sure?" } %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "New Dojo", new_dojo_path %>

dojo_dashboard_I/app/views/dojos/new.html.erb
<h1>Add a new Dojo</h1>
<form action="/dojos" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label>Branch:</label>
		<input type="text" name=dojo[branch] value="<%= @dojo.branch %>">
	</p>
	<p>
		<label>Street:</label>
		<input type="text" name=dojo[street] value="<%= @dojo.street %>">
	</p>
	<p>
		<label>City:</label>
		<input type="text" name=dojo[city] value="<%= @dojo.city %>">
	</p>
	<p>
		<label>State:</label>
		<input type="text" name=dojo[state] value="<%= @dojo.state %>">
	</p>
	<input type="submit" name="Create Dojo">	
</form>
<%= link_to "Back", root_path %>

dojo_dashboard_I/app/views/dojos/show.html.erb
<h1><%= @dojo.branch %></h1>

<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>


<p>Addres: <%= @dojo.street %></p>
<p>City: <%= @dojo.city %> State: <%= @dojo.state %></p>

<h2>Student Roster</h2>

<table>
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
		<th>Actions</th>
	</thead>
	<tbody>
	<% @students.each do |student| %>
		<tr>
			<td><%= student.first_name %></td>
			<td><%= student.last_name %></td>
			<td><%= student.email %></td>
			<td>
				<%= link_to "Show", dojo_student_path(@dojo, student) %> |
				<%= link_to "Edit", edit_dojo_student_path(@dojo, student) %> | 
				<%= link_to "Delete", dojo_student_path(@dojo, student), data: { method: :delete, confirm: "Are you sure?" } %>
			</td>
		</tr>
	<% end %>		
	</tbody>
</table> 

<%= link_to "Home", root_path %> | <%= link_to "Edit", edit_dojo_path(@dojo) %> | <%= link_to "Add Student", new_dojo_student_path(@dojo) %>

dojo_dashboard_I/app/views/students/edit.html.erb
<h1>Edit <%= "#{@student.first_name} #{@student.last_name}" %></h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>	

<form action="/dojos/<%= @student.dojo_id %>/students/<%= @student.id %>" method="post">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label>First Name:</label>
		<input type="text" name=student[first_name] value="<%= @student.first_name %>">
	</p>
	<p>
		<label>Last Name:</label>
		<input type="text" name="student[last_name]" value="<%= @student.last_name %>">
	</p>
	<p>
		<label>Email:</label>
		<input type="text" name=student[email] value="<%= @student.email %>">
	</p>
	<p>
		<label>Dojo:</label>
		<select name="student[dojo_id]">
			<% @dojos.each do |dojo| %>
				<% if dojo.id == @student.dojo_id %>
					<option selected value="<%= dojo.id %>"><%= dojo.branch %></option>
				<% else %>
					<option value="<%= dojo.id %>"><%= dojo.branch %></option>
				<% end %>
			<% end %>	
		</select>
	</p>
	<input type="submit" name="Create Student">	
</form>

<%= link_to "Home", root_path %> | <%= link_to "#{@student.first_name}", dojo_student_path(@student.dojo_id, @student) %>

dojo_dashboard_I/app/views/students/new.html.erb
<h1>New Student</h1>

<form action="/dojos/<%= @dojo.id %>/students" method ="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<p>
		<label>First Name:</label>
		<input type="text" name=student[first_name]>
	</p>
	<p>
		<label>Last Name:</label>
		<input type="text" name="student[last_name]">
	</p>
	<p>
		<label>Email:</label>
		<input type="text" name=student[email]>
	</p>
  <p>
		<label>Dojo:</label>
		<select name="student[dojo_id]">
			<% @dojos.each do |dojo| %>
				<% if dojo == @dojo %>
					<option selected value="<%= dojo.id %>"><%= dojo.branch %></option>
				<% else %>
					<option value="<%= dojo.id %>"><%= dojo.branch %></option>
				<% end %>
			<% end %>	
		</select>
	</p>
	<input type="submit" name="Create Student">
</form>
<%= link_to "Home", root_path %> | <%= link_to "#{@dojo.branch}", @dojo %>

dojo_dashboard_I/app/views/students/show.html.erb
<h1><%= "#{@student.branch}'s #{@student.first_name} #{@student.last_name}" %></h1>

<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>


<h3>Email: <%= "#{@student.email}" %></h3>

<h2>Cohort</h2>

<table>
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email</th>
	</thead>
	<tbody>
		<% @cohort.each do |student| %>
		<tr>
			<td><%= student.first_name %></td>
			<td><%= student.last_name %></td>
			<td><%= student.email %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "Home", root_path %> | <%= link_to "Edit", edit_dojo_student_path(@student.dojo_id, @student.id) %>